/*******************************************************************************
 * Copyright © 2006-2011, www.processconfiguration.com
 *   
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *   
 * Contributors:
 *      Marcello La Rosa - initial API and implementation, subsequent revisions
 *      Florian Gottschalk - individualizer for YAWL
 *      Possakorn Pitayarojanakul - integration with Configurator and Individualizer
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.04.14 at 01:59:07 PM EST 
//

package com.processconfiguration.cmap;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for nofiType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="nofiType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="value">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="minIncrease" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                 &lt;attribute name="maxDecrease" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                 &lt;attribute name="thresIncrease" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *                 &lt;attribute name="creationMode" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="restict"/>
 *                       &lt;enumeration value="keep"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="condition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="taskId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nofiType", propOrder = { "value" })
public class NofiType {

	@XmlElement(required = true)
	protected List<NofiType.Value> value;
	@XmlAttribute(required = true)
	protected String taskId;

	/**
	 * Gets the value of the value property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the value property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getValue().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link NofiType.Value }
	 * 
	 * 
	 */
	public List<NofiType.Value> getValue() {
		if (value == null) {
			value = new ArrayList<NofiType.Value>();
		}
		return this.value;
	}

	/**
	 * Gets the value of the taskId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTaskId() {
		return taskId;
	}

	/**
	 * Sets the value of the taskId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTaskId(String value) {
		this.taskId = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="minIncrease" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
	 *       &lt;attribute name="maxDecrease" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
	 *       &lt;attribute name="thresIncrease" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
	 *       &lt;attribute name="creationMode" use="required">
	 *         &lt;simpleType>
	 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
	 *             &lt;enumeration value="restict"/>
	 *             &lt;enumeration value="keep"/>
	 *           &lt;/restriction>
	 *         &lt;/simpleType>
	 *       &lt;/attribute>
	 *       &lt;attribute name="condition" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "")
	public static class Value {

		@XmlAttribute(required = true)
		@XmlSchemaType(name = "positiveInteger")
		protected BigInteger minIncrease;
		@XmlAttribute(required = true)
		@XmlSchemaType(name = "positiveInteger")
		protected BigInteger maxDecrease;
		@XmlAttribute(required = true)
		@XmlSchemaType(name = "positiveInteger")
		protected BigInteger thresIncrease;
		@XmlAttribute(required = true)
		protected String creationMode;
		@XmlAttribute(required = true)
		protected String condition;

		/**
		 * Gets the value of the minIncrease property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getMinIncrease() {
			return minIncrease;
		}

		/**
		 * Sets the value of the minIncrease property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setMinIncrease(BigInteger value) {
			this.minIncrease = value;
		}

		/**
		 * Gets the value of the maxDecrease property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getMaxDecrease() {
			return maxDecrease;
		}

		/**
		 * Sets the value of the maxDecrease property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setMaxDecrease(BigInteger value) {
			this.maxDecrease = value;
		}

		/**
		 * Gets the value of the thresIncrease property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getThresIncrease() {
			return thresIncrease;
		}

		/**
		 * Sets the value of the thresIncrease property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setThresIncrease(BigInteger value) {
			this.thresIncrease = value;
		}

		/**
		 * Gets the value of the creationMode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCreationMode() {
			return creationMode;
		}

		/**
		 * Sets the value of the creationMode property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCreationMode(String value) {
			this.creationMode = value;
		}

		/**
		 * Gets the value of the condition property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCondition() {
			return condition;
		}

		/**
		 * Sets the value of the condition property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setCondition(String value) {
			this.condition = value;
		}

	}

}
