package org.apromore.canoniser.bpmn;

// Java 2 Standard packages
import java.io.File;

/**
 * Shared directory locations for test data.
 *
 * @author <a href="mailto:simon.raboczi@uqconnect.edu.au">Simon Raboczi</a>
 */
public interface TestConstants {

    /** Source for BPMN test data. */
    final static File BPMN_MODELS_DIR = new File("src/test/resources/BPMN_models/");

    /** Destination for converted documents generated by tests. */
    final static File OUTPUT_DIR = new File("target/");

    /** Source for ANF and CPF test data. */
    final static File CANONICAL_MODELS_DIR = new File("src/test/resources/canonical_models/");
}
