	
insert into users (lastname,firstname,email,username,passwd) values ("La Rosa", "Marcello", "m.larosa@qut.edu.au", "larosa", "");
insert into users (lastname,firstname,email,username,passwd) values ("Fauvet","Marie","marie-christine.fauvet@qut.edu.au","fauvet", "");
insert into users (lastname,firstname,email,username,passwd) values ("Ter Hofstede","Arthur","arthur@yawlfoundation.org","arthur", "");
insert into users (lastname,firstname,email,username,passwd) values ("Garcia-Banuelos","Luciano","lgbanuelos@gmail.com","luciano", "");
insert into users (lastname,firstname,email,username,passwd) values ("Dijkman","Remco","R.M.Dijkman@tue.nl","remco", "");
insert into users (lastname,firstname,email,username,passwd) values ("Alshareef","Abdul","aah.shareef@gmail.com","abdul", "");
insert into users (lastname,firstname,email,username,passwd) values ("","Mehrad",null,"mehrad", "");
insert into users (lastname,firstname,email,username,passwd) values ("Ekanayake","Chathura",null,"chathura", null);
insert into users  (firstname, username, passwd) values ("Hajo", "hajo", "");
insert into users  (firstname, username, passwd) values ("Barbara", "barbara", "");
insert into users  (firstname, username, passwd) values ("Anne", "anne", "");
insert into users  (firstname, username, passwd) values ("icsoc 2010", "icsoc", "Macri");
insert into users  (firstname, username, passwd) values ("guest", "guest", "");
insert into users  (firstname, username, passwd) values ("Reina", "reina", "");
insert into users  (firstname, username, passwd) values ("Inam", "inam", "");
insert into users  (firstname, username, passwd) values ("Naiad", "naiad", "");
insert into users (lastname,firstname,email,username,passwd) values ("Alrashed","Fahad","fahadakr@gmail.com","fahad", null);
insert into users  (firstname, username, passwd) values ("Public", "public", "");
insert into native_types values ("EPML 2.0","epml");
insert into native_types values ("XPDL 2.1","xpdl");
