FROM openjdk:8

RUN groupadd -r apromore && useradd --no-log-init -r -g apromore apromore

RUN apt-get -y update \
&& apt-get -y install vim \
&& apt-get -y install maven \
&& apt-get -y install ant \
&& apt-get -y clean 


Copy ./Supplements/liblpsolve55/* /usr/local/lib/
WORKDIR /usr/local/lib/

RUN ldconfig \
&& chmod 755 /usr/local/lib/liblpsolve55j.so

ENV LD_LIBRARY_PATH /usr/local/lib


WORKDIR /opt/apromore/
# Check .dockerignore
COPY ./ ./ 

RUN chown -R apromore:apromore /opt/apromore/ \
&& chmod -R 777 /opt/apromore/

USER apromore
EXPOSE 9000

RUN mvn clean install
# RUN ant create-h2

CMD [ "ant", "start-virgo-nix" ]
