FROM openjdk:8 as intial

RUN groupadd -r apromore && useradd --no-log-init -r -g apromore apromore

RUN apt-get -y update \
&& apt-get -y install vim \
&& apt-get -y install maven \
&& apt-get -y install ant \
&& apt-get -y clean 


WORKDIR /opt/apromore/
COPY ./ ./

RUN chown -R apromore:apromore /opt/apromore/ \
&& chmod -R 777 /opt/apromore/

Run ant create-h2
# && mvn clean install \



USER apromore
EXPOSE 9000

CMD [ "ant", "start-virgo-nix"]

# for production, add failur policy to always restart the container!