package org.apromore.dao.model;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.springframework.beans.factory.annotation.Configurable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Fragment generated by hbm2java
 */
@Entity
@Table(name = "fragment")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Configurable("fragment")
public class Fragment implements Serializable {

    /** Hard coded for interoperability. */
    private static final long serialVersionUID = -9072538545638485548L;

    private String fragmentId;
    private Integer propagationPolicy;
    private Set<FragmentVersion> fragmentVersions = new HashSet<FragmentVersion>(0);


    public Fragment() { }


    @Id
    @Column(name = "fragment_id", unique = true, nullable = false, length = 40)
    public String getFragmentId() {
        return this.fragmentId;
    }

    public void setFragmentId(String newFragmentId) {
        this.fragmentId = newFragmentId;
    }


    @Column(name = "propagation_policy")
    public Integer getPropagationPolicy() {
        return this.propagationPolicy;
    }

    public void setPropagationPolicy(final Integer newPropagationPolicy) {
        this.propagationPolicy = newPropagationPolicy;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "fragment")
    public Set<FragmentVersion> getFragmentVersions() {
        return this.fragmentVersions;
    }

    public void setFragmentVersions(final Set<FragmentVersion> newFragmentVersions) {
        this.fragmentVersions = newFragmentVersions;
    }

}


