package org.apromore.dao.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * HeadVersion0 generated by hbm2java
 */
@Entity
@Table(name = "head_versions0")
public class HeadVersion0 implements Serializable {


    private HeadVersion0Id id;


    /**
     * Default Constructor.
     */
    public HeadVersion0() {
    }


    @EmbeddedId
    @AttributeOverrides({
            @AttributeOverride(name = "processId", column = @Column(name = "processId")),
            @AttributeOverride(name = "version", column = @Column(name = "version", length = 20))})
    public HeadVersion0Id getId() {
        return this.id;
    }

    public void setId(HeadVersion0Id id) {
        this.id = id;
    }

}


