/*
 * Copyright © 2009-2018 The Apromore Initiative.
 *
 * This file is part of "Apromore".
 *
 * "Apromore" is free software; you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 3 of the
 * License, or (at your option) any later version.
 *
 * "Apromore" is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program.
 * If not, see <http://www.gnu.org/licenses/lgpl-3.0.html>.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.03 at 05:04:23 PM CET 
//

package org.yawlfoundation.yawlschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TypeType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="namespace" type="{http://www.yawlfoundation.org/yawlschema}NamespacePrefixType"/>
 *         &lt;element name="typeName" type="{http://www.yawlfoundation.org/yawlschema}TypeNameType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeType", propOrder = { "namespace", "typeName" })
public class TypeType {

	@XmlElement(required = true)
	protected NamespacePrefixType namespace;
	@XmlElement(required = true)
	protected TypeNameType typeName;

	/**
	 * Gets the value of the namespace property.
	 * 
	 * @return possible object is {@link NamespacePrefixType }
	 * 
	 */
	public NamespacePrefixType getNamespace() {
		return namespace;
	}

	/**
	 * Sets the value of the namespace property.
	 * 
	 * @param value
	 *            allowed object is {@link NamespacePrefixType }
	 * 
	 */
	public void setNamespace(NamespacePrefixType value) {
		this.namespace = value;
	}

	/**
	 * Gets the value of the typeName property.
	 * 
	 * @return possible object is {@link TypeNameType }
	 * 
	 */
	public TypeNameType getTypeName() {
		return typeName;
	}

	/**
	 * Sets the value of the typeName property.
	 * 
	 * @param value
	 *            allowed object is {@link TypeNameType }
	 * 
	 */
	public void setTypeName(TypeNameType value) {
		this.typeName = value;
	}

}
