package org.apromore.logfilter.criteria.model;

/**
 * 
 * @author Bruce Nguyen
 *
 */
public enum Type {
    CONCEPT_NAME, CASE_VARIANT, DIRECT_FOLLOW, EVENTUAL_FOLLOW, LIFECYCLE_TRANSITION,
    ORG_GROUP, ORG_RESOURCE, ORG_ROLE, TIME_TIMESTAMP, DURATION_RANGE,
    TIME_STARTRANGE, TIME_ENDRANGE, //2019-09-20
    TIME_DURATION,
    CASE_ID, CASE_UTILIZATION, //2019-10-10
    DURATION_TOTAL_PROCESSING, DURATION_AVERAGE_PROCESSING, DURATION_MAX_PROCESSING,//2019-10-08
    DURATION_TOTAL_WAITING, DURATION_AVERAGE_WAITING, DURATION_MAX_WAITING,//2019-10-08
    UNKNOWN
}
