package org.apromore.logfilter.criteria.model;

/**
 * 
 * @author Bruce Nguyen
 * Modified by Chii Chang
 *
 */
public enum Type {
    CONCEPT_NAME, CASE_VARIANT, DIRECT_FOLLOW, EVENTUAL_FOLLOW, LIFECYCLE_TRANSITION,
    ORG_GROUP, ORG_RESOURCE, ORG_ROLE, TIME_TIMESTAMP, DURATION_RANGE,
    TIME_STARTRANGE, TIME_ENDRANGE,
    CASE_ID, CASE_UTILIZATION,
    DURATION_TOTAL_PROCESSING, DURATION_AVERAGE_PROCESSING, DURATION_MAX_PROCESSING,
    DURATION_TOTAL_WAITING, DURATION_AVERAGE_WAITING, DURATION_MAX_WAITING,
    REWORK_REPETITION,
    UNKNOWN
}
