call mvn install:install-file -Dfile=breeze.jar -DgroupId=org.ZK -DartifactId=breeze -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=ckez.jar -DgroupId=org.ZK -DartifactId=ckez -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=fckez.jar -DgroupId=org.ZK -DartifactId=fckez -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=flashchart.jar -DgroupId=org.ZK -DartifactId=flashchart -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=gmapsz.jar -DgroupId=org.ZK -DartifactId=gmapsz -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=sapphire.jar -DgroupId=org.ZK -DartifactId=sapphire -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=silvertail.jar -DgroupId=org.ZK -DartifactId=silvertail -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=timelinez.jar -DgroupId=org.ZK -DartifactId=timelinez -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=timeplotz.jar -DgroupId=org.ZK -DartifactId=timeplotz -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zcommon.jar -DgroupId=org.ZK -DartifactId=zcommon -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zcommons-el.jar -DgroupId=org.ZK -DartifactId=zcommon-el -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zhtml.jar -DgroupId=org.ZK -DartifactId=zhtml -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zk.jar -DgroupId=org.ZK -DartifactId=zk -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zkex.jar -DgroupId=org.ZK -DartifactId=zkex -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zkmax.jar -DgroupId=org.ZK -DartifactId=zkmax -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zkplus.jar -DgroupId=org.ZK -DartifactId=zkplus -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zkspring-core.jar -DgroupId=org.ZK -DartifactId=zkspring-core -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zml.jar -DgroupId=org.ZK -DartifactId=zml -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zul.jar -DgroupId=org.ZK -DartifactId=zul -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zuljsp.jar -DgroupId=org.ZK -DartifactId=zuljsp -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
call mvn install:install-file -Dfile=zweb.jar -DgroupId=org.ZK -DartifactId=zweb -Dversion=5.0.12 -Dpackaging=jar -DgeneratePom=true
