FROM adoptopenjdk:11-jre-hotspot as builder
WORKDIR application
ARG JAR_FILE=./build/libs/Apromore-Core-7.21-SNAPSHOT.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM adoptopenjdk:11-jre-hotspot
# ****************************************************************
# Replace line above with commands below for Japanese environment
# ****************************************************************
# FROM adoptopenjdk:11-jre-hotspot as run
# RUN apt-get update && apt-get upgrade -y
# RUN apt-get install -y language-pack-ja
# RUN apt-get install fonts-noto-cjk
# RUN export LANG=ja_JP.UTF-8
# RUN echo "export LANG=ja_JP.UTF-8" >> /etc/locale.conf
# ENV LANG ja_JP.UTF-8
# ENV LC_ALL ja_JP.UTF-8

WORKDIR application
COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
