package org.apromore.dao.model;

import org.eclipse.persistence.annotations.CacheCoordinationType;
import org.eclipse.persistence.annotations.CacheType;
import org.eclipse.persistence.config.CacheIsolationType;
import org.springframework.beans.factory.annotation.Configurable;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Cacheable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * Content generated by hbm2java
 */
@Entity
@Table(name = "content")
@Configurable("content")
@Cacheable(true)
@org.eclipse.persistence.annotations.Cache(type = CacheType.SOFT_WEAK, isolation = CacheIsolationType.SHARED, expiry = 60000, size = 1000, alwaysRefresh = true, disableHits = true, coordinationType = CacheCoordinationType.INVALIDATE_CHANGED_OBJECTS)
public class Content implements Serializable {

    private Integer id;
    private String code;

    private Node boundaryE;
    private Node boundaryS;

    private Set<Node> nodes = new HashSet<Node>(0);
    private Set<Edge> edges = new HashSet<Edge>(0);

    /**
     * Public Constructor.
     */
    public Content() { }



    /**
     * returns the Id of this Object.
     * @return the id
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    /**
     * Sets the Id of this Object
     * @param id the new Id.
     */
    public void setId(final Integer id) {
        this.id = id;
    }



    @Column(name = "code", length = 65535)
    public String getCode() {
        return this.code;
    }

    public void setCode(final String newContentHash) {
        this.code = newContentHash;
    }



    @ManyToOne
    @JoinColumn(name = "boundary_e")
    public Node getBoundaryE() {
        return this.boundaryE;
    }

    public void setBoundaryE(Node nodeByBoundaryE) {
        this.boundaryE = nodeByBoundaryE;
    }

    @ManyToOne
    @JoinColumn(name = "boundary_s")
    public Node getBoundaryS() {
        return this.boundaryS;
    }

    public void setBoundaryS(Node nodeByBoundaryS) {
        this.boundaryS = nodeByBoundaryS;
    }



    @OneToMany(mappedBy = "content", cascade = CascadeType.ALL, orphanRemoval = true)
    public Set<Node> getNodes() {
        return this.nodes;
    }

    public void setNodes(final Set<Node> newNodes) {
        this.nodes = newNodes;
    }

    @OneToMany(mappedBy = "content", cascade = CascadeType.ALL, orphanRemoval = true)
    public Set<Edge> getEdges() {
        return this.edges;
    }

    public void setEdges(final Set<Edge> newEdges) {
        this.edges = newEdges;
    }

}


