
package org.apromore.manager.da;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.7
 * Tue Jul 13 17:53:31 EST 2010
 * Generated source version: 2.2.7
 * 
 */

public final class DAManagerPortType_DAManager_Client {

    private static final QName SERVICE_NAME = new QName("http://www.apromore.org/data_access/service_manager", "DAManagerService");

    private DAManagerPortType_DAManager_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = DAManagerService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DAManagerService ss = new DAManagerService(wsdlURL, SERVICE_NAME);
        DAManagerPortType port = ss.getDAManager();  
        
        {
        System.out.println("Invoking deleteProcessVersions...");
        org.apromore.manager.model_da.DeleteProcessVersionsInputMsgType _deleteProcessVersions_payload = new org.apromore.manager.model_da.DeleteProcessVersionsInputMsgType();
        java.util.List<org.apromore.manager.model_da.ProcessVersionIdentifierType> _deleteProcessVersions_payloadProcessVersionIdentifier = new java.util.ArrayList<org.apromore.manager.model_da.ProcessVersionIdentifierType>();
        org.apromore.manager.model_da.ProcessVersionIdentifierType _deleteProcessVersions_payloadProcessVersionIdentifierVal1 = new org.apromore.manager.model_da.ProcessVersionIdentifierType();
        java.util.List<java.lang.String> _deleteProcessVersions_payloadProcessVersionIdentifierVal1VersionName = new java.util.ArrayList<java.lang.String>();
        _deleteProcessVersions_payloadProcessVersionIdentifierVal1.getVersionName().addAll(_deleteProcessVersions_payloadProcessVersionIdentifierVal1VersionName);
        _deleteProcessVersions_payloadProcessVersionIdentifierVal1.setProcessid(Integer.valueOf(-124319782));
        _deleteProcessVersions_payloadProcessVersionIdentifier.add(_deleteProcessVersions_payloadProcessVersionIdentifierVal1);
        _deleteProcessVersions_payload.getProcessVersionIdentifier().addAll(_deleteProcessVersions_payloadProcessVersionIdentifier);
        org.apromore.manager.model_da.DeleteProcessVersionsOutputMsgType _deleteProcessVersions__return = port.deleteProcessVersions(_deleteProcessVersions_payload);
        System.out.println("deleteProcessVersions.result=" + _deleteProcessVersions__return);


        }
        {
        System.out.println("Invoking writeUser...");
        org.apromore.manager.model_da.WriteUserInputMsgType _writeUser_payload = new org.apromore.manager.model_da.WriteUserInputMsgType();
        org.apromore.manager.model_da.UserType _writeUser_payloadUser = new org.apromore.manager.model_da.UserType();
        java.util.List<org.apromore.manager.model_da.SearchHistoriesType> _writeUser_payloadUserSearchHistories = new java.util.ArrayList<org.apromore.manager.model_da.SearchHistoriesType>();
        org.apromore.manager.model_da.SearchHistoriesType _writeUser_payloadUserSearchHistoriesVal1 = new org.apromore.manager.model_da.SearchHistoriesType();
        _writeUser_payloadUserSearchHistoriesVal1.setSearch("Search1230613145");
        _writeUser_payloadUserSearchHistoriesVal1.setNum(Integer.valueOf(-817224790));
        _writeUser_payloadUserSearchHistories.add(_writeUser_payloadUserSearchHistoriesVal1);
        _writeUser_payloadUser.getSearchHistories().addAll(_writeUser_payloadUserSearchHistories);
        _writeUser_payloadUser.setFirstname("Firstname-1065332288");
        _writeUser_payloadUser.setLastname("Lastname-1135350578");
        _writeUser_payloadUser.setEmail("Email1112121582");
        _writeUser_payloadUser.setUsername("Username1690053045");
        _writeUser_payloadUser.setPasswd("Passwd1974096108");
        _writeUser_payload.setUser(_writeUser_payloadUser);
        org.apromore.manager.model_da.WriteUserOutputMsgType _writeUser__return = port.writeUser(_writeUser_payload);
        System.out.println("writeUser.result=" + _writeUser__return);


        }
        {
        System.out.println("Invoking readNative...");
        org.apromore.manager.model_da.ReadNativeInputMsgType _readNative_payload = new org.apromore.manager.model_da.ReadNativeInputMsgType();
        _readNative_payload.setProcessId(Integer.valueOf(-1663098260));
        _readNative_payload.setVersion("Version1989721059");
        _readNative_payload.setNativeType("NativeType1037552134");
        org.apromore.manager.model_da.ReadNativeOutputMsgType _readNative__return = port.readNative(_readNative_payload);
        System.out.println("readNative.result=" + _readNative__return);


        }
        {
        System.out.println("Invoking deleteEditSession...");
        org.apromore.manager.model_da.DeleteEditSessionInputMsgType _deleteEditSession_payload = new org.apromore.manager.model_da.DeleteEditSessionInputMsgType();
        _deleteEditSession_payload.setEditSessionCode(Integer.valueOf(-1738827687));
        org.apromore.manager.model_da.DeleteEditSessionOutputMsgType _deleteEditSession__return = port.deleteEditSession(_deleteEditSession_payload);
        System.out.println("deleteEditSession.result=" + _deleteEditSession__return);


        }
        {
        System.out.println("Invoking readEditSession...");
        org.apromore.manager.model_da.ReadEditSessionInputMsgType _readEditSession_payload = new org.apromore.manager.model_da.ReadEditSessionInputMsgType();
        _readEditSession_payload.setEditSessionCode(Integer.valueOf(-1125844375));
        org.apromore.manager.model_da.ReadEditSessionOutputMsgType _readEditSession__return = port.readEditSession(_readEditSession_payload);
        System.out.println("readEditSession.result=" + _readEditSession__return);


        }
        {
        System.out.println("Invoking readDomains...");
        org.apromore.manager.model_da.ReadDomainsInputMsgType _readDomains_payload = new org.apromore.manager.model_da.ReadDomainsInputMsgType();
        _readDomains_payload.setEmpty("Empty1638837629");
        org.apromore.manager.model_da.ReadDomainsOutputMsgType _readDomains__return = port.readDomains(_readDomains_payload);
        System.out.println("readDomains.result=" + _readDomains__return);


        }
        {
        System.out.println("Invoking writeEditSession...");
        org.apromore.manager.model_da.WriteEditSessionInputMsgType _writeEditSession_payload = new org.apromore.manager.model_da.WriteEditSessionInputMsgType();
        org.apromore.manager.model_da.EditSessionType _writeEditSession_payloadEditSession = new org.apromore.manager.model_da.EditSessionType();
        _writeEditSession_payloadEditSession.setUsername("Username971047910");
        _writeEditSession_payloadEditSession.setNativeType("NativeType1044892176");
        _writeEditSession_payloadEditSession.setProcessId(Integer.valueOf(-622627776));
        _writeEditSession_payloadEditSession.setProcessName("ProcessName324066395");
        _writeEditSession_payloadEditSession.setVersionName("VersionName-1296169713");
        _writeEditSession_payloadEditSession.setDomain("Domain1285013788");
        _writeEditSession_payload.setEditSession(_writeEditSession_payloadEditSession);
        org.apromore.manager.model_da.WriteEditSessionOutputMsgType _writeEditSession__return = port.writeEditSession(_writeEditSession_payload);
        System.out.println("writeEditSession.result=" + _writeEditSession__return);


        }
        {
        System.out.println("Invoking readFormats...");
        org.apromore.manager.model_da.ReadFormatsInputMsgType _readFormats_payload = new org.apromore.manager.model_da.ReadFormatsInputMsgType();
        _readFormats_payload.setEmpty("Empty-2142885986");
        org.apromore.manager.model_da.ReadFormatsOutputMsgType _readFormats__return = port.readFormats(_readFormats_payload);
        System.out.println("readFormats.result=" + _readFormats__return);


        }
        {
        System.out.println("Invoking readCanonicalAnf...");
        org.apromore.manager.model_da.ReadCanonicalAnfInputMsgType _readCanonicalAnf_payload = new org.apromore.manager.model_da.ReadCanonicalAnfInputMsgType();
        _readCanonicalAnf_payload.setProcessId(Integer.valueOf(525011024));
        _readCanonicalAnf_payload.setVersion("Version470955191");
        org.apromore.manager.model_da.ReadCanonicalAnfOutputMsgType _readCanonicalAnf__return = port.readCanonicalAnf(_readCanonicalAnf_payload);
        System.out.println("readCanonicalAnf.result=" + _readCanonicalAnf__return);


        }
        {
        System.out.println("Invoking readUser...");
        org.apromore.manager.model_da.ReadUserInputMsgType _readUser_payload = new org.apromore.manager.model_da.ReadUserInputMsgType();
        _readUser_payload.setUsername("Username570612284");
        org.apromore.manager.model_da.ReadUserOutputMsgType _readUser__return = port.readUser(_readUser_payload);
        System.out.println("readUser.result=" + _readUser__return);


        }
        {
        System.out.println("Invoking editDataProcess...");
        org.apromore.manager.model_da.EditDataProcessInputMsgType _editDataProcess_payload = new org.apromore.manager.model_da.EditDataProcessInputMsgType();
        _editDataProcess_payload.setProcessName("ProcessName1131147520");
        _editDataProcess_payload.setId(Integer.valueOf(841294897));
        _editDataProcess_payload.setDomain("Domain1573939917");
        _editDataProcess_payload.setOwner("Owner1869059027");
        _editDataProcess_payload.setRanking(Integer.valueOf(759710873));
        _editDataProcess_payload.setNewName("NewName1769765103");
        _editDataProcess_payload.setPreName("PreName908253058");
        org.apromore.manager.model_da.EditDataProcessOutputMsgType _editDataProcess__return = port.editDataProcess(_editDataProcess_payload);
        System.out.println("editDataProcess.result=" + _editDataProcess__return);


        }
        {
        System.out.println("Invoking readProcessSummaries...");
        org.apromore.manager.model_da.ReadProcessSummariesInputMsgType _readProcessSummaries_payload = new org.apromore.manager.model_da.ReadProcessSummariesInputMsgType();
        _readProcessSummaries_payload.setSearchExpression("SearchExpression658094371");
        org.apromore.manager.model_da.ReadProcessSummariesOutputMsgType _readProcessSummaries__return = port.readProcessSummaries(_readProcessSummaries_payload);
        System.out.println("readProcessSummaries.result=" + _readProcessSummaries__return);


        }

        System.exit(0);
    }

}
