package org.apromore.dao.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.springframework.beans.factory.annotation.Configurable;

/**
 * FragmentVersionDag generated by hbm2java
 */
@Entity
@Table(name = "fragment_version_dag",
        uniqueConstraints = {
                @UniqueConstraint(columnNames = {"fragmentVersionId", "childFragmentVersionId", "pocketId"})
        }
)
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Configurable("fragmentVersionDag")
public class FragmentVersionDag implements Serializable {

    /**
     * Hard coded for interoperability.
     */
    private static final long serialVersionUID = -9072539074338485548L;

    private Integer id;
    private String pocketId;

    private FragmentVersion fragmentVersionId;
    private FragmentVersion childFragmentVersionId;

    /**
     * Public Constructor.
     */
    public FragmentVersionDag() { }


    /**
     * returns the Id of this Object.
     * @return the id
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    /**
     * Sets the Id of this Object
     * @param id the new Id.
     */
    public void setId(final Integer id) {
        this.id = id;
    }


    @Column(name = "pocketId", length = 40)
    public String getPocketId() {
        return this.pocketId;
    }

    public void setPocketId(final String pocketId) {
        this.pocketId = pocketId;
    }


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fragmentVersionId", nullable = false)
    public FragmentVersion getFragmentVersionId() {
        return this.fragmentVersionId;
    }

    public void setFragmentVersionId(final FragmentVersion newFragmentVersion) {
        this.fragmentVersionId = newFragmentVersion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "childFragmentVersionId", nullable = false)
    public FragmentVersion getChildFragmentVersionId() {
        return this.childFragmentVersionId;
    }

    public void setChildFragmentVersionId(final FragmentVersion newChildFragmentVersion) {
        this.childFragmentVersionId = newChildFragmentVersion;
    }
}
