package org.apromore.dao.model;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.springframework.beans.factory.annotation.Configurable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * NonPocketVertex generated by hbm2java
 */
@Entity
@Table(name = "non_pocket_vertex")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Configurable("nonPocketVertex")
public class NonPocketVertex implements Serializable {

    /** Hard coded for interoperability. */
    private static final long serialVersionUID = -9072538657838485548L;

    private String vid;


    public NonPocketVertex() { }


    @Id
    @Column(name = "vid", unique = true, nullable = false, length = 40)
    public String getVid() {
        return this.vid;
    }

    public void setVid(final String newVid) {
        this.vid = newVid;
    }

}


