package org.apromore.dao.model;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.springframework.beans.factory.annotation.Configurable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * NonPocketNode generated by hbm2java
 */
@Entity
@Table(name = "non_pocket_node")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Configurable("nonPocketNode")
public class NonPocketNode implements Serializable {

    /** Hard coded for interoperability. */
    private static final long serialVersionUID = -9072538657838485548L;

    private Integer vid;


    public NonPocketNode() { }


    @Id
    @Column(name = "vid", unique = true, nullable = false, length = 40)
    public Integer getVid() {
        return this.vid;
    }

    public void setVid(final Integer newVid) {
        this.vid = newVid;
    }

}


