/*******************************************************************************
 * Copyright © 2006-2011, www.processconfiguration.com
 *   
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *   
 * Contributors:
 *      Marcello La Rosa - initial API and implementation, subsequent revisions
 *      Florian Gottschalk - individualizer for YAWL
 *      Possakorn Pitayarojanakul - integration with Configurator and Individualizer
 ******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.03 at 05:04:23 PM CET 
//

package org.yawlfoundation.yawlschema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for FlowsIntoType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="FlowsIntoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nextElementRef" type="{http://www.yawlfoundation.org/yawlschema}ExternalNetElementType"/>
 *         &lt;element name="predicate" type="{http://www.yawlfoundation.org/yawlschema}PredicateType" minOccurs="0"/>
 *         &lt;element name="isDefaultFlow" type="{http://www.yawlfoundation.org/yawlschema}NullType" minOccurs="0"/>
 *         &lt;element name="documentation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlowsIntoType", propOrder = { "nextElementRef", "predicate",
		"isDefaultFlow", "documentation" })
public class FlowsIntoType {

	@XmlElement(required = true)
	protected ExternalNetElementType nextElementRef;
	protected PredicateType predicate;
	protected String isDefaultFlow;
	protected String documentation;

	/**
	 * Gets the value of the nextElementRef property.
	 * 
	 * @return possible object is {@link ExternalNetElementType }
	 * 
	 */
	public ExternalNetElementType getNextElementRef() {
		return nextElementRef;
	}

	/**
	 * Sets the value of the nextElementRef property.
	 * 
	 * @param value
	 *            allowed object is {@link ExternalNetElementType }
	 * 
	 */
	public void setNextElementRef(ExternalNetElementType value) {
		this.nextElementRef = value;
	}

	/**
	 * Gets the value of the predicate property.
	 * 
	 * @return possible object is {@link PredicateType }
	 * 
	 */
	public PredicateType getPredicate() {
		return predicate;
	}

	/**
	 * Sets the value of the predicate property.
	 * 
	 * @param value
	 *            allowed object is {@link PredicateType }
	 * 
	 */
	public void setPredicate(PredicateType value) {
		this.predicate = value;
	}

	/**
	 * Gets the value of the isDefaultFlow property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIsDefaultFlow() {
		return isDefaultFlow;
	}

	/**
	 * Sets the value of the isDefaultFlow property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setIsDefaultFlow(String value) {
		this.isDefaultFlow = value;
	}

	/**
	 * Gets the value of the documentation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDocumentation() {
		return documentation;
	}

	/**
	 * Sets the value of the documentation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDocumentation(String value) {
		this.documentation = value;
	}

}
