<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://www.apromore.org/canoniser/service_manager" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tnsx="http://www.apromore.org/canoniser/model_manager" xmlns:tns="http://www.apromore.org/canoniser/service_manager" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://www.apromore.org/canoniser/model_manager" location="canoniser_managerX.xsd">
    </import>
  <message name="CanoniseProcessOutputMsg">
    <part name="payload" element="tnsx:CanoniseProcessOutputMsg">
    </part>
  </message>
  <message name="CanoniseProcessInputMsg">
    <part name="payload" element="tnsx:CanoniseProcessInputMsg">
    </part>
  </message>
  <portType name="CanoniserManagerPortType">
    <operation name="CanoniseProcess">
      <input name="CanoniseProcessRequest" message="tns:CanoniseProcessInputMsg">
    </input>
      <output name="CanoniseProcessResponse" message="tns:CanoniseProcessOutputMsg">
    </output>
    </operation>
  </portType>
  <binding name="CanoniserManagerBinding" type="tns:CanoniserManagerPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="CanoniseProcess">
      <soap:operation style="document"/>
      <input name="CanoniseProcessRequest">
        <soap:body use="literal"/>
      </input>
      <output name="CanoniseProcessResponse">
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="CanoniserManagerService">
    <port name="CanoniserManager" binding="tns:CanoniserManagerBinding">
      <soap:address location="http://localhost:8080/Apromore-canoniser/services/CanoniserManager"/>
    </port>
  </service>
</definitions>
