
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.apromore.manager.da;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.7
 * Fri Jul 23 17:11:00 EST 2010
 * Generated source version: 2.2.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "DAManagerService",
                      portName = "DAManager",
                      targetNamespace = "http://www.apromore.org/data_access/service_manager",
                      wsdlLocation = "http://localhost:8080/Apromore-dataAccess/services/DAManager?wsdl",
                      endpointInterface = "org.apromore.manager.da.DAManagerPortType")
                      
public class DAManagerPortTypeImpl implements DAManagerPortType {

    private static final Logger LOG = Logger.getLogger(DAManagerPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#deleteProcessVersions(org.apromore.manager.model_da.DeleteProcessVersionsInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.DeleteProcessVersionsOutputMsgType deleteProcessVersions(org.apromore.manager.model_da.DeleteProcessVersionsInputMsgType payload) { 
        LOG.info("Executing operation deleteProcessVersions");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.DeleteProcessVersionsOutputMsgType _return = new org.apromore.manager.model_da.DeleteProcessVersionsOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message1792607304");
            _returnResult.setCode(Integer.valueOf(1146565920));
            _return.setResult(_returnResult);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#writeUser(org.apromore.manager.model_da.WriteUserInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.WriteUserOutputMsgType writeUser(org.apromore.manager.model_da.WriteUserInputMsgType payload) { 
        LOG.info("Executing operation writeUser");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.WriteUserOutputMsgType _return = new org.apromore.manager.model_da.WriteUserOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message-1398122781");
            _returnResult.setCode(Integer.valueOf(-1755478833));
            _return.setResult(_returnResult);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#readNativeTypes(org.apromore.manager.model_da.ReadNativeTypesInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.ReadNativeTypesOutputMsgType readNativeTypes(org.apromore.manager.model_da.ReadNativeTypesInputMsgType payload) { 
        LOG.info("Executing operation readNativeTypes");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.ReadNativeTypesOutputMsgType _return = new org.apromore.manager.model_da.ReadNativeTypesOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message462509332");
            _returnResult.setCode(Integer.valueOf(-581206831));
            _return.setResult(_returnResult);
            org.apromore.manager.model_da.NativeTypesType _returnNativeTypes = new org.apromore.manager.model_da.NativeTypesType();
            java.util.List<org.apromore.manager.model_da.FormatTypeType> _returnNativeTypesNativeType = new java.util.ArrayList<org.apromore.manager.model_da.FormatTypeType>();
            org.apromore.manager.model_da.FormatTypeType _returnNativeTypesNativeTypeVal1 = new org.apromore.manager.model_da.FormatTypeType();
            _returnNativeTypesNativeTypeVal1.setFormat("Format1126349377");
            _returnNativeTypesNativeTypeVal1.setExtension("Extension244879455");
            _returnNativeTypesNativeType.add(_returnNativeTypesNativeTypeVal1);
            _returnNativeTypes.getNativeType().addAll(_returnNativeTypesNativeType);
            _return.setNativeTypes(_returnNativeTypes);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#deleteEditSession(org.apromore.manager.model_da.DeleteEditSessionInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.DeleteEditSessionOutputMsgType deleteEditSession(org.apromore.manager.model_da.DeleteEditSessionInputMsgType payload) { 
        LOG.info("Executing operation deleteEditSession");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.DeleteEditSessionOutputMsgType _return = new org.apromore.manager.model_da.DeleteEditSessionOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message161576420");
            _returnResult.setCode(Integer.valueOf(1514642561));
            _return.setResult(_returnResult);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#readEditSession(org.apromore.manager.model_da.ReadEditSessionInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.ReadEditSessionOutputMsgType readEditSession(org.apromore.manager.model_da.ReadEditSessionInputMsgType payload) { 
        LOG.info("Executing operation readEditSession");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.ReadEditSessionOutputMsgType _return = new org.apromore.manager.model_da.ReadEditSessionOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message138428984");
            _returnResult.setCode(Integer.valueOf(-713457458));
            _return.setResult(_returnResult);
            javax.activation.DataHandler _returnNative = null;
            _return.setNative(_returnNative);
            org.apromore.manager.model_da.EditSessionType _returnEditSession = new org.apromore.manager.model_da.EditSessionType();
            _returnEditSession.setUsername("Username-1210643750");
            _returnEditSession.setNativeType("NativeType-669949560");
            _returnEditSession.setProcessId(Integer.valueOf(-2028457762));
            _returnEditSession.setProcessName("ProcessName996443615");
            _returnEditSession.setVersionName("VersionName-1480685260");
            _returnEditSession.setDomain("Domain-2051570779");
            _return.setEditSession(_returnEditSession);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#readDomains(org.apromore.manager.model_da.ReadDomainsInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.ReadDomainsOutputMsgType readDomains(org.apromore.manager.model_da.ReadDomainsInputMsgType payload) { 
        LOG.info("Executing operation readDomains");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.ReadDomainsOutputMsgType _return = new org.apromore.manager.model_da.ReadDomainsOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message-52006062");
            _returnResult.setCode(Integer.valueOf(434500036));
            _return.setResult(_returnResult);
            org.apromore.manager.model_da.DomainsType _returnDomains = new org.apromore.manager.model_da.DomainsType();
            java.util.List<java.lang.String> _returnDomainsDomain = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnDomainsDomainVal1 = "_returnDomainsDomainVal-1813583495";
            _returnDomainsDomain.add(_returnDomainsDomainVal1);
            _returnDomains.getDomain().addAll(_returnDomainsDomain);
            _return.setDomains(_returnDomains);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#writeEditSession(org.apromore.manager.model_da.WriteEditSessionInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.WriteEditSessionOutputMsgType writeEditSession(org.apromore.manager.model_da.WriteEditSessionInputMsgType payload) { 
        LOG.info("Executing operation writeEditSession");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.WriteEditSessionOutputMsgType _return = new org.apromore.manager.model_da.WriteEditSessionOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message-1524679389");
            _returnResult.setCode(Integer.valueOf(1195884816));
            _return.setResult(_returnResult);
            _return.setEditSessionCode(Integer.valueOf(889653223));
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#readCanonicalAnf(org.apromore.manager.model_da.ReadCanonicalAnfInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.ReadCanonicalAnfOutputMsgType readCanonicalAnf(org.apromore.manager.model_da.ReadCanonicalAnfInputMsgType payload) { 
        LOG.info("Executing operation readCanonicalAnf");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.ReadCanonicalAnfOutputMsgType _return = new org.apromore.manager.model_da.ReadCanonicalAnfOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message980535535");
            _returnResult.setCode(Integer.valueOf(-1217347273));
            _return.setResult(_returnResult);
            javax.activation.DataHandler _returnCpf = null;
            _return.setCpf(_returnCpf);
            javax.activation.DataHandler _returnAnf = null;
            _return.setAnf(_returnAnf);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#readUser(org.apromore.manager.model_da.ReadUserInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.ReadUserOutputMsgType readUser(org.apromore.manager.model_da.ReadUserInputMsgType payload) { 
        LOG.info("Executing operation readUser");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.ReadUserOutputMsgType _return = new org.apromore.manager.model_da.ReadUserOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message-1239032698");
            _returnResult.setCode(Integer.valueOf(-1084591130));
            _return.setResult(_returnResult);
            org.apromore.manager.model_da.UserType _returnUser = new org.apromore.manager.model_da.UserType();
            java.util.List<org.apromore.manager.model_da.SearchHistoriesType> _returnUserSearchHistories = new java.util.ArrayList<org.apromore.manager.model_da.SearchHistoriesType>();
            org.apromore.manager.model_da.SearchHistoriesType _returnUserSearchHistoriesVal1 = new org.apromore.manager.model_da.SearchHistoriesType();
            _returnUserSearchHistoriesVal1.setSearch("Search-117461425");
            _returnUserSearchHistoriesVal1.setNum(Integer.valueOf(-1806027604));
            _returnUserSearchHistories.add(_returnUserSearchHistoriesVal1);
            _returnUser.getSearchHistories().addAll(_returnUserSearchHistories);
            _returnUser.setFirstname("Firstname-1915827993");
            _returnUser.setLastname("Lastname262843614");
            _returnUser.setEmail("Email1338992059");
            _returnUser.setUsername("Username-940110655");
            _returnUser.setPasswd("Passwd334039358");
            _return.setUser(_returnUser);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#editDataProcess(org.apromore.manager.model_da.EditDataProcessInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.EditDataProcessOutputMsgType editDataProcess(org.apromore.manager.model_da.EditDataProcessInputMsgType payload) { 
        LOG.info("Executing operation editDataProcess");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.EditDataProcessOutputMsgType _return = new org.apromore.manager.model_da.EditDataProcessOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message336906475");
            _returnResult.setCode(Integer.valueOf(1944233967));
            _return.setResult(_returnResult);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#readFormat(org.apromore.manager.model_da.ReadFormatInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.ReadFormatOutputMsgType readFormat(org.apromore.manager.model_da.ReadFormatInputMsgType payload) { 
        LOG.info("Executing operation readFormat");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.ReadFormatOutputMsgType _return = new org.apromore.manager.model_da.ReadFormatOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message-158074799");
            _returnResult.setCode(Integer.valueOf(847527109));
            _return.setResult(_returnResult);
            javax.activation.DataHandler _returnNative = null;
            _return.setNative(_returnNative);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see org.apromore.manager.da.DAManagerPortType#readProcessSummaries(org.apromore.manager.model_da.ReadProcessSummariesInputMsgType  payload )*
     */
    public org.apromore.manager.model_da.ReadProcessSummariesOutputMsgType readProcessSummaries(org.apromore.manager.model_da.ReadProcessSummariesInputMsgType payload) { 
        LOG.info("Executing operation readProcessSummaries");
        System.out.println(payload);
        try {
            org.apromore.manager.model_da.ReadProcessSummariesOutputMsgType _return = new org.apromore.manager.model_da.ReadProcessSummariesOutputMsgType();
            org.apromore.manager.model_da.ResultType _returnResult = new org.apromore.manager.model_da.ResultType();
            _returnResult.setMessage("Message-1577155345");
            _returnResult.setCode(Integer.valueOf(-2039906121));
            _return.setResult(_returnResult);
            org.apromore.manager.model_da.ProcessSummariesType _returnProcessSummaries = new org.apromore.manager.model_da.ProcessSummariesType();
            java.util.List<org.apromore.manager.model_da.ProcessSummaryType> _returnProcessSummariesProcessSummary = new java.util.ArrayList<org.apromore.manager.model_da.ProcessSummaryType>();
            org.apromore.manager.model_da.ProcessSummaryType _returnProcessSummariesProcessSummaryVal1 = new org.apromore.manager.model_da.ProcessSummaryType();
            java.util.List<org.apromore.manager.model_da.VersionSummaryType> _returnProcessSummariesProcessSummaryVal1VersionSummaries = new java.util.ArrayList<org.apromore.manager.model_da.VersionSummaryType>();
            _returnProcessSummariesProcessSummaryVal1.getVersionSummaries().addAll(_returnProcessSummariesProcessSummaryVal1VersionSummaries);
            _returnProcessSummariesProcessSummaryVal1.setOriginalNativeType("OriginalNativeType-26888396");
            _returnProcessSummariesProcessSummaryVal1.setName("Name1621535863");
            _returnProcessSummariesProcessSummaryVal1.setId(Integer.valueOf(-2080471917));
            _returnProcessSummariesProcessSummaryVal1.setDomain("Domain-1512494944");
            _returnProcessSummariesProcessSummaryVal1.setRanking(Integer.valueOf(-1882487835));
            _returnProcessSummariesProcessSummaryVal1.setLastVersion("LastVersion-1129472541");
            _returnProcessSummariesProcessSummaryVal1.setOwner("Owner1924796043");
            _returnProcessSummariesProcessSummary.add(_returnProcessSummariesProcessSummaryVal1);
            _returnProcessSummaries.getProcessSummary().addAll(_returnProcessSummariesProcessSummary);
            _return.setProcessSummaries(_returnProcessSummaries);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
