package org.apromore.dao.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import java.util.HashSet;
import java.util.Set;

import org.eclipse.persistence.annotations.Cache;
import org.eclipse.persistence.annotations.CacheCoordinationType;
import org.springframework.beans.factory.annotation.Configurable;

/**
 * ResourceRef generated by hbm2java
 */
@Entity
@Table(name = "resource_ref")
@Configurable("resourceRef")
@Cache(expiry = 180000, size = 1000, coordinationType = CacheCoordinationType.INVALIDATE_CHANGED_OBJECTS)
public class ResourceRef implements java.io.Serializable {

    private Integer id;
    private String qualifier;

    private Node node;
    private Resource resource;
    private Set<ResourceRefAttribute> resourceRefAttributes = new HashSet<>();


    /**
     * Public Constructor.
     */
    public ResourceRef() {
    }



    /**
     * returns the Id of this Object.
     * @return the id
     */
    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    /**
     * Sets the Id of this Object
     * @param id the new Id.
     */
    public void setId(final Integer id) {
        this.id = id;
    }


    @Column(name = "qualifier")
    public String getQualifier() {
        return this.qualifier;
    }

    public void setQualifier(String qualifier) {
        this.qualifier = qualifier;
    }


    @ManyToOne
    @JoinColumn(name = "nodeId")
    public Node getNode() {
        return this.node;
    }

    public void setNode(Node node) {
        this.node = node;
    }

    @ManyToOne
    @JoinColumn(name = "resourceId")
    public Resource getResource() {
        return this.resource;
    }

    public void setResource(Resource resourceType) {
        this.resource = resourceType;
    }


    @OneToMany(mappedBy = "resourceRef", cascade = CascadeType.ALL, orphanRemoval = true)
    public Set<ResourceRefAttribute> getResourceRefAttributes() {
        return this.resourceRefAttributes;
    }

    public void setResourceRefAttributes(Set<ResourceRefAttribute> resourceRefTypeAttributes) {
        this.resourceRefAttributes = resourceRefTypeAttributes;
    }

}


