<!--
  Copyright © 2006-2011, www.processconfiguration.com
    
  All rights reserved. This program and the accompanying materials
  are made available under the terms of the Eclipse Public License v1.0
  which accompanies this distribution, and is available at
  http://www.eclipse.org/legal/epl-v10.html
    
  Contributors:
       Marcello La Rosa - initial API and implementation, subsequent revisions
       Florian Gottschalk - individualizer for YAWL
       Possakorn Pitayarojanakul - integration with Configurator and Individualizer
-->
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><ns2:DCL xmlns:ns2="http://www.processconfiguration.com/DCL" reference="www.processconfiguration.com" author="M. La Rosa, J. Lux" name="Picture post-production"><Fact id="f1"><description>Low (≤ 250,000 US)</description><value>true</value><deviates>true</deviates></Fact><Fact id="f10"><description>Film shooting</description><value>false</value><deviates>false</deviates></Fact><Fact id="f11"><description>Online cut</description><value>true</value><deviates>false</deviates></Fact><Fact id="f12"><description>Film-based cut</description><value>false</value><deviates>false</deviates></Fact><Fact id="f13"><description>Tape finish</description><value>true</value><deviates>false</deviates></Fact><Fact id="f14"><description>Film finish</description><value>false</value><deviates>true</deviates></Fact><Fact id="f15"><description>New Media finish</description><value>true</value><deviates>true</deviates></Fact><Fact id="f16"><description>Analogue tape</description><value>false</value><deviates>false</deviates></Fact><Fact id="f17"><description>SD Digital tape</description><value>true</value><deviates>false</deviates></Fact><Fact id="f18"><description>HD Digital tape</description><value>false</value><deviates>false</deviates></Fact><Fact id="f19"><description>16mm film</description><value>false</value><deviates>false</deviates></Fact><Fact id="f2"><description>Medium (&gt; 250,000 US, ≤ 1.5mil US)</description><value>false</value><deviates>true</deviates></Fact><Fact id="f20"><description>35mm film</description><value>false</value><deviates>false</deviates></Fact><Fact id="f21"><description>65mm film</description><value>false</value><deviates>false</deviates></Fact><Fact id="f3"><description>High (&gt; 1.5mil US)</description><value>false</value><deviates>false</deviates></Fact><Fact id="f4"><description>Cinema</description><value>false</value><deviates>true</deviates></Fact><Fact id="f5"><description>TV</description><value>true</value><deviates>true</deviates></Fact><Fact id="f6"><description>Home</description><value>true</value><deviates>false</deviates></Fact><Fact id="f7"><description>Mobile</description><value>false</value><deviates>false</deviates></Fact><Fact id="f8"><description>Internet</description><value>false</value><deviates>false</deviates></Fact><Fact id="f9"><description>Tape shooting</description><value>true</value><deviates>false</deviates></Fact></ns2:DCL>
