//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.25 at 04:41:24 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.apromore.org/CPF")
package org.apromore.cpf;
